Repository Yz4230/HP_monitor, pull requests merged in 2020-04, with the labels that each got.

#5 Fix: Typo
  crawlers/common.py
  utils.py
Labels: readable

#8 Hotfix/twitter maxlength
  API/line_api.py
  API/tokens.py
  API/twitter_api.py
  main.py
  requirements.txt
  test/test_text_rendering.py
  utils.py
Labels: hotfix

#12 add discord api and appended *.log in gitignore
  .gitignore
  API/agents/discord.py
  tokens.schema.json
Labels: enhancement
